src/controllers/representadas.py
from database import db
from flask import render_template, request, redirect, url_for, flash, Blueprint, current_app

from models.tables import Representadas, Representadascontatos

bp_representadas = Blueprint("representadas", __name__, template_folder="../templates")


# Cadastrar REPRESENTATADAS
@bp_representadas.route('/representadas', methods=['GET', 'POST'])
def representadas():
    repres = db.session.query(Representadas).all()
    if request.method == 'POST':
        razaosocial = request.form['razaosocial']
        cnpj = request.form['cnpj']
        inscricaoestadual = request.form['inscricaoestadual']
        telefone = request.form['telefone']
        endereco = request.form['endereco']
        bairro = request.form['bairro']
        cidade = request.form['cidade']
        estado = request.form['estado']
        cep = request.form['cep']
        comissao = request.form['comissao']
        repres = Representadas(Razaosocial=razaosocial, Cnpj=cnpj, Inscricaoestadual=inscricaoestadual,
                               Telefone=telefone,
                               Endereco=endereco, Bairro=bairro, Cidade=cidade, Estado=estado, Cep=cep,
                               Comissao=comissao)
        db.session.add(repres)
        db.session.commit()
        # flash("Dados inseridos com sucesso!")
        return redirect(url_for('representadas.representadas'))

    return render_template('representadas.html', repre=repres)


@bp_representadas.route('/editrepresentada/', methods=['GET', 'POST'])
def editrepresentada():
    my_data = Representadas.query.get(request.form.get("idrepresentadas"))
    if request.method == 'POST':
        my_data.razaosocial = request.form['razaosocial']
        my_data.cnpj = request.form['cnpj']
        my_data.inscricaoestadual = request.form['inscricaoestadual']
        my_data.telefone = request.form['telefone']
        my_data.endereco = request.form['endereco']
        my_data.bairro = request.form['bairro']
        my_data.cidade = request.form['cidade']
        my_data.estado = request.form['estado']
        my_data.cep = request.form['cep']
        my_data.comissao = request.form['comissao']
        return redirect(url_for('representadas.representadas', repres=my_data))
    return render_template('representadas.html')


@bp_representadas.route('/deleterepres/<Idrepresentada>/', methods=['GET'])
def deleterepres(Idrepresentada):
    my_data = Representadas.query.get(Idrepresentada)
    db.session.delete(my_data)
    db.session.commit()
    # flash("Item deletado com sucesso!")
    return render_template('representadas.html')

# cadastrar contatos das representadas
@bp_representadas.route('/representadacontatos', methods=['GET', 'POST'])
def representadacontatos():
    reprecont = db.session.query(Representadascontatos).all()
    if request.method == 'POST':
        # flash('Cadastrado realizado')
        nome = request.form['nome']
        cargo = request.form['cargo']
        telefone = request.form['telefone']
        celular = request.form['celular']
        email = request.form['email']
        reprecont = Representadascontatos(Nome=nome, Cargo=cargo, Telefone=telefone, Celular=celular, Email=email)
        db.session.add(reprecont)
        db.session.commit()
        return redirect(url_for('representadacontatos'))
    return render_template('representadacontatos.html', listacontatosrepresentada=reprecont)


# editar contatos das representadas
@bp_representadas.route('/editarrepresentadacontatos', methods=['GET', 'POST'])
def editarrepresentadacontatos():
    my_data = Representadascontatos.query.get(request.form.get("Idcontatorepresentada"))
    if request.method == 'POST':
        # flash('Cadastrado realizado')
        my_data.nome = request.form['nome']
        my_data.cargo = request.form['cargo']
        my_data.telefone = request.form['telefone']
        my_data.celular = request.form['celular']
        my_data.email = request.form['email']
        return redirect(url_for('representadacontatos', listacontatosrepresentada=my_data))
    return render_template('representadacontatos.html')


@bp_representadas.route('/deleterepresentadacontatos/<Idcontatorepresentada>', methods=['GET'])
def deleterepresentadacontatos(Idcontatorepresentada):
    my_data = Representadascontatos.query.get(Idcontatorepresentada)
    db.session.delete(my_data)
    db.session.commit()
    # flash("Item deletado com sucesso!")
    return render_template('representadacontatos.html')

src/controllers/transportadoras.py
from flask import render_template, request, redirect, url_for, flash, Blueprint, current_app
from database import db
from models.tables import Transportadoras

bp_transportadoras = Blueprint("transportadoras", __name__,template_folder="../templates")


# CADASTRO DE TRANSPORTADORA
@bp_transportadoras.route('/transportadoras', methods=['GET', 'POST'])
def transportadoras():
    my_data = db.session.query(Transportadoras).all()
    if request.method == "POST":
        transportadora = request.form['transportadora']
        cidade = request.form['cidade']
        estado = request.form['estado']
        telefone = request.form['telefone']
        my_data = Transportadoras(Transportadora=transportadora, Cidade=cidade, Estado=estado, Telefone=telefone)
        db.session.add(my_data)
        db.session.commit()
        #flash("Dados inseridos com sucesso!")
        return redirect(url_for('transportadoras.transportadoras'))

    return render_template('transportadoras.html', listatransportadoras=my_data)


# ATUALIZAÇÃO DO CADASTRO DA TRANSPORTADORA 

@bp_transportadoras.route('/updatetransp/', methods=['POST', 'GET'])
def updatetransp():
    if request.method == "POST":
        my_data = Transportadoras.query.get(request.form.get('idtransportadora'))
        my_data.idtransportadora = request.form['idtransportadora']
        my_data.Transportadora = request.form['transportadora']
        my_data.Cidade = request.form['cidade']
        my_data.Estado = request.form['estado']
        my_data.Telefone = request.form['telefone']
        db.session.commit()
        #flash("Dados alterados com sucesso!")
        return redirect(url_for('transportadoras.transportadoras'))
    return render_template('transportadoras.html')


# DELETAR A TRANSPORTADORA
@bp_transportadoras.route('/deletetransp/<idtransportadora>/', methods=['GET'])
def deletetransp(idtransportadora):
    my_data = Transportadoras.query.get(idtransportadora)
    db.session.delete(my_data)
    db.session.commit()
    #flash("Item deletado com sucesso!")
    return redirect(url_for('transportadoras.transportadoras'))

src/templates/clientescompletos.html
{%extends "base.html"%}

<html>


{%block content%}
EXPLAIN SELECT * FROM clientes INNER JOIN clientesenderecos ON clientes.idcliente=clientesenderecos.idclientesenderecos
INNER JOIN clientescontatos on clientes.idcliente=clientescontatos.idcliente INNER JOIN contatos_realizados ON
clientes.idcliente=contatos_realizados.idcliente

{%endblock%}>
</html>

src/templates/clientescontatos.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

{% block content %}

<div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron p-3">
                    <h2>Contatos</h2>
                        <!-- Botão para acionar modal -->
                        <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#modalclicontatos">Cadastrar Contatos</button>
                </div>
            </div>
        </div>  

    <!-- Modal -->
    <div class="modal fade" id="modalclicontatos" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabe" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cadastro de Contatos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('default.clientescontatos') }}" method="POST">
                        <div class="form-group" method="POST">
                        
                            <div class="form-group" method="POST">
                                                          
                                <label>Código Cliente:</label>
                                <input type="text" class="form-control" name="idcliente">
                            </div>


                            <div class="form-group" method="POST">
                                <label>Nome:</label>
                                <input type="text" class="form-control" name="nome"/>
                            </div>  

                            <div class="form-group" method="POST">
                                <label>Cargo:</label>
                                <input type="text" class="form-control" name="cargo">
                            </div>
                            
                            <div class="form-group" method="POST">
                                <label>Telefone:</label>
                                <input type="text" class="form-control" name="telefone">
                            </div>

                            <div class="form-group" method="POST">
                                <label>Ramal:</label>
                                <input type="text" class="form-control" name="ramal">
                            </div>

                            <div>
                                <label>Celular:</label>
                                <input type="text" class="form-control" name="celular">
                            </div>
                            
                            <div class="form-group" method="POST">
                                <label>e-mail:</label>
                                <input type="text" class="form-control" name="email">
                            </div>

                        </div>
                        
                     <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                        <button type="button" class="btn btn-primary">Salvar</button>
                    </div>

                    </form>
                </div>
               
            </div>
        </div>
    </div>
</div>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">X</span>
                    </button>
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

      
<table class="table">
    <tr>
        <td colspan="8">Cliente</td>
    </tr>
	<tr>
       <!-- <td>Código Contato</td> -->
        <td>Nome</td>
		<td>Cargo</td>
		<td>Telefone</td>
		<td>Ramal</td>
		<td>Celular</td>
        <td>e-mail</td>
		<td>Ação</td>
	</tr>
 
{% for row in listacontatos %}
    <tr >
        <td colspan="8">{{row.clicon.Razao_social}} 
    </tr>
	<tr>
       <!-- <td>{{row.Idclientecontato}}</td>-->
		<td>{{row.Nome}}</td>
		<td>{{row.Cargo}}</td>
		<td>{{row.Telefone}}</td>
		<td>{{row.Ramal}}</td>
        <td>{{row.Celular}}</td>
        <td>{{row.Email}}</td>
       
		<td>
            <a href="/default.editclientescontatos/{{row.Idclientecontato}}" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modaleditclientescontatos{{row.Idclientecontato}}">Editar</a>
			<a href="/default.deleteclientescontatos/{{row.Idclientecontato}}" class="btn btn-danger btn-sm" onclick="return confirm(' tem certeza que deseja apagar o contato?')">Apagar</a>    
		</td>
	</tr>

    <!-- Modal edit contato-->
    <div class="modal fade" id="modaleditclientescontatos{{row.Idclientecontato}}" tabindex="-1" role="dialog" aria-labelledby="modaleditclientescontatos{{row.Idclientecontato}}"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Editar Contato</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{url_for('default.editclientescontatos')}}" method="POST">
                        <div class="form-group" method="POST">
                            
                            <div class="form-group" method="POST">
                              
                                <input type="hidden" class="form-control" name="idclientecontato" value="{{row.Idclientecontato}}">
                                <label>Código Cliente:</label>
                                <input type="text" class="form-control" name="idcliente" value="{{row.clicon.Razao_social}}">
                            </div>

                            <div class="form-group" method="POST">
                                <label>Nome:</label>
                                <input type="text" class="form-control" name="nome" value="{{row.Nome}}" >
                            </div>

                            <div class="form-group" method="POST">
                                <label>Cargo:</label>
                                <input type="text" class="form-control" name="cargo" value="{{row.Cargo}}">
                            </div>
    
                            <div class="form-group" method="POST">
                                <label>Telefone:</label>
                                <input type="text" class="form-control" name="telefone" value="{{row.Telefone}}">
                            </div>
    
                            <div class="form-group" method="POST">
                                <label>Ramal:</label>
                                <input type="text" class="form-control" name="ramal" value="{{row.Ramal}}">
                            </div>

                            <div class="form-group" method="POST">
                                <label>Celular:</label>
                                <input type="text" class="form-control" name="celular" value="{{row.Celular}}">
                            </div>

                            <div class="form-group" method="POST">
                                <label>e-mail:</label>
                                <input type="text" class="form-control" name="email" value="{{row.Email}}">
                            </div>
    
                        </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                <button type="Submit" class="btn btn-primary">Salvar </button>
                            </div>
    
                    </form>
                </div>
                
            </div>
        </div>
    </div>
    </div>

{% endfor %}
</table>

	</body>


</div>

</html>
{% endblock %}

src/templates/clientesenderecos.html
{% extends "base.html" %}
<!DOCTYPE html>
<meta charset="utf-8">

{% block content %}
<html>
	<body> 

	<!-- SELECIONAR O CLIENTE , VIA CAIXA DE PESQUISA  -->


<div class="container">
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                    <span aria-hidden="true">X</span>
                </button>
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}


    <!-- Botão para acionar modal -->
        <div class="row">
            <div class="col-md-12">
                <div class="jumbotron p-3">
                    <h2>Endereços</h2>
                    <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#modalClienteEndereco">Cadastrar Endereço</button>

                </div>
            </div>
        </div>


<!-- Modal cadastro endereços -->
<div class="modal fade" id="modalClienteEndereco" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Endereços</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="{{url_for('default.clientesenderecos')}}" method="POST">

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="finalidade" id="inlineRadio1" value="faturamento">
                        <label class="form-check-label" for="inlineRadio1">Faturamento</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="finalidade" id="inlineRadio2" value="cobranca">
                        <label class="form-check-label" for="inlineRadio2">Cobrança</label>
                    </div>

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="finalidade" id="inlineRadio3" value="Entrega">
                        <label class="form-check-label" for="inlineRadio3">Entrega</label>
                    </div>

                    <div class="form-group">
                        <label >Endereço:</label>
                        <input type="text" class="form-control" name="endereco">

                    </div>

                    <div class="form-group" method="POST">
                        <label>Bairro:</label>
                        <input type="text" class="form-control" name="bairro">
                    </div>

                    <div class="form-group" method="POST">
                        <label>Cidade:</label>
                        <input type="text" class="form-control" name="cidade">
                    </div>

                    <div class="form-group" method="POST">
                        <label>Estado:</label>
                        <input type="text" class="form-control" name="estado">
                    </div>

                    <div class="form-group" method="POST">
                        <label>CEP:</label>
                        <input type="text" class="form-control" name="cep">
                    </div>

            </div>
                    <div class="modal-footer">
                    
                        <button type="submit" class="btn btn-primary">Enviar</button>
                        
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    
                    </div>
                </form>
        </div>
    </div>
</div>
<br>
<table class="table">
    
    <tr>
        <th colspan="8">Cliente</th>
    </tr>
    <tr>

        <th>Codigo</th>
        <th>Finalidade</th>
        <th>Endereço</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>CEP</th>
        <th>Ação</th>
    </tr>
{%for row in listaenderecos %}
    <tr >
        <td colspan="8">{{row.cliend.Razao_social}}</td>
    </tr>
    <tr>
        <td>{{row.Idclientesenderecos}} </td>
       
        <td>{{row.Finalidade}}</td>
        <td>{{row.Endereco}}</td>
        <td>{{row.Bairro}}</td>
        <td>{{row.Cidade}}</td>
        <td>{{row.Estado}}</td>
        <td>{{row.Cep}}</td>
        <td>Ação</td>
    </tr>
{%endfor%}
</table>



</div>
            


	

	</body>

</html>
{% endblock %}

src/templates/index.html
{%extends "base.html"%}

{% block content%}
<html>
    <body>
        

    </body>
</html>
{%endblock%}

src/templates/javascript.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <form action="" method="post">
    Valor Unitário: <input type="text" name="valor_unitario" id="valor_unitario" />
    Quantidade: <input type="text" name="qnt" id="qnt" value="0" />
    Imposto: <input type="text" name="ipi" id="ipi" value="0">
    Total: <input type="text" name="total" id="total" readonly="readonly" />

    
  </form>

<script type="text/javascript">
    function id(el) {
                    return document.getElementById( el );
                    }
   // onde a conta é feita
    function total( un, qnt, ipi)   
                                {
                                return (parseFloat(un.replace(',', '.'), 10) * parseFloat(ipi.replace(',','.'),10)) * parseFloat(qnt.replace(',', '.'), 10);
                                }
window.onload = function() {
                            id('valor_unitario').addEventListener('keyup', function() {
                            var result = total( this.value , id('qnt').value );
                            id('total').value = String(result.toFixed(2)).formatMoney();
                            });

                            id('qnt').addEventListener('keyup', function(){
                            var result = total( id('valor_unitario').value , this.value );
                                id('total').value = String(result.toFixed(2)).formatMoney();
                            });

                            id('ipi').addEventListener('keyup', function() {
                            var result = total( this.value, id('ipi').value, this.value);
                            id('total').value = String(result.toFixed(2)).formatMoney();
                            });

                            }

String.prototype.formatMoney = function() {
                                            var v = this;

                                            if(v.indexOf('.') === -1) {
                                                                        v = v.replace(/([\d]+)/, "$1,00");
                                                                        }

                                                v = v.replace(/([\d]+)\.([\d]{1})$/, "$1,$20");
                                                v = v.replace(/([\d]+)\.([\d]{2})$/, "$1,$2");
                                                v = v.replace(/([\d]+)([\d]{3}),([\d]{2})$/, "$1.$2,$3");

                                                return v;
                                            };
</script>

</body>
</html>

src/templates/orcamentos.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

{% endblock %}

src/templates/pedido.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}


{% endblock %}

src/templates/pyscript.html
<html>

<head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <!--ONDE FICAM AS BIBLIOTECAS PYTHON -->
    <py-env>
    
        

    </py-env>

</head>

<body>
    <py-script>
        print("Let's compute π:")
        
    </py-script>
</body>

</html>

src/templates/solicitacoes.html
{% extends "base.html" %}

{% block title %} {% endblock %}

{% block content %}

{% endblock %}

src/templates/transportadoras.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron p-3">
                <h2>Transportadoras</h2> 
                    <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodaltransportadora" >Cadastrar</button>
            </div>
        </div>
    </div>

<!-- Modal cadastro -->
      <div class="modal fade" id="mymodaltransportadora" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="mymodaltransportadora">Cadastrar Transportadora</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                
                    <div class="modal-body">
                        
                        <form action="{{url_for('transportadoras.transportadoras')}}" method="POST">
                           
                                    <div class="form-group" method="POST">
                                     
                                        <label>Transportadora:</label>
                                        <input type="text" class="form-control" name="transportadora">
                                    </div>
                                    
                                    <div class="form-group" method="POST">
                                        <label>Cidade:</label> 
                                        <input type="text" class="form-control" name="cidade">
                                    </div>
                
                                    <div class="form-group" method="POST">
                                        <label>Estado:</label>
                                        <input type="text" class="form-control" name="estado">
                                    </div>
                
                                    <div class="form-group" method="POST">
                                        <label>Telefone:</label>
                                        <input type="text" class="form-control" name="telefone" >
                                    </div>
                
                                    <div class="form-group">
                                        <button class="btn btn-primary" type="submit">Enviar</button>
                                    </div>
                                
                    </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                            </div>
                            
                        </form>

                    </div>

            </div>
        
        </div>
</div>

</div>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                   {% for message in messages %}
                        <div class="alert alert-success alert-dismissable" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">X</span>
                            </button>
                            {{message}}
                        </div>
                     {% endfor %}
                {% endif %}
            {% endwith %}
       
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Transportadora</th>
        <th>Cidade</th>
        <th>Estado</th>
        <th>Telefone</th>
        <th>Ação</th>
    </tr>

{% for row in listatransportadoras %}
    <tr>
        <td>{{row.idtransportadora}}</td>
        <td>{{row.Transportadora}}</td>
        <td>{{row.Cidade}}</td>
        <td>{{row.Estado}}</td>
        <td>{{row.Telefone}}</td>
        <td> 
            <a href="/updatetransp{{row.idtransportadora}}" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#modaledittransportadora{{row.idtransportadora}}">Editar</a>
            <a href="/deletetransp/{{row.idtransportadora}}" class="btn btn-danger btn-sm" onclick="return confirm('Tem certeza que deseja apagar')">Apagar</a>  
        </td>
    </tr>


    <!--MODAL EDITAR cadastro -->
    <div class="modal fade bd-example-modal-lg"  id="modaledittransportadora{{row.idtransportadora}}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-tittle">Editar Dados</h4>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('transportadoras.updatetransp') }}" method="POST">
                        <div class="form-group">
                            <input type="hidden" name="idtransportadora" value="{{row.idtransportadora}}">
                                <label>Transportadora:</label>
                            <input type="text" class="form-control" name="transportadora"  value="{{row.Transportadora}}">
                        </div>
                        
                        <div class="form-group" method="POST">
                            <label>Cidade:</label> 
                            <input type="text" class="form-control" name="cidade" value="{{row.Cidade}}">
                        </div>
    
                        <div class="form-group" method="POST">
                            <label>Estado:</label>
                            <input type="text" class="form-control" name="estado" value="{{row.Estado}}">
                        </div>
    
                        <div class="form-group" method="POST">
                            <label>Telefone:</label>
                            <input type="text" class="form-control" name="telefone" value="{{row.Telefone}}">
                        </div>
    
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Atualizar</button>
                        </div>
                    </form>
    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                </div>
            </div>
        </div>
    </div>

{%endfor%} 
</table>


{% endblock %}
</html>